version: '3.8'

services:
  web3hub-api:
    build: .
    ports:
      - "3501:3500"  # Map the exposed port 3500 from the Dockerfile to the same port on the host
    environment:
      - NODE_ENV=development  # Set environment variables if needed
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/
          ignore:
            - node_modules/
        - action: sync
          path: ./ligo
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
