# SPDX-FileCopyrightText: 2021 TQ Tezos
# SPDX-License-Identifier: LicenseRef-MIT-TQ

resolver: lorentz/template/snapshot.yaml

packages:
  - lorentz
  - lorentz/template
  - haskell

# See extra-deps in template/snapshot.yaml
